### ISSUE TITLE
cell_spec bold will not test condition

### ISSUE THREAD

**Issue by vancelopez** [haozhu233/kableExtra#105]
Using `ifelse` in the `bold` argument of `cell_spec` does not work. Using the documentation example, I changed the "mpg" input to have a `bold` argument instead of `color`. In this example, all rows of "mpg" will be bold type face:

```
mtcars[1:10, 1:2] %>%
  mutate(
    car = row.names(.),
    # You don't need format = "html" if you have ever defined options(knitr.table.format)
    mpg = cell_spec(mpg, "html", bold = ifelse(mpg > 20, TRUE, FALSE)),
    cyl = cell_spec(cyl, "html", color = "white", align = "c", angle = 45, 
                    background = factor(cyl, c(4, 6, 8), 
                                        c("#666666", "#999999", "#BBBBBB")))
  ) %>%
  select(car, mpg, cyl) %>%
  knitr::kable("html", escape = F) %>%
  kable_styling("striped", full_width = F)
```
Session info:
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] kableExtra_0.6.1.9000 bindrcpp_0.2          FCNN4R_0.6.2          Rcpp_0.12.13          dplyr_0.7.4           doParallel_1.0.11     iterators_1.0.8      
 [8] foreach_1.4.3         caret_6.0-78          ggplot2_2.2.1         lattice_0.20-35      

loaded via a namespace (and not attached):
 [1] httr_1.3.1          ddalpha_1.3.1       tidyr_0.7.2         sfsmisc_1.1-1       jsonlite_1.5        viridisLite_0.2.0   splines_3.4.0      
 [8] prodlim_1.6.1       assertthat_0.2.0    highr_0.6           stats4_3.4.0        DRR_0.0.2           yaml_2.1.14         robustbase_0.92-8  
[15] ipred_0.9-6         backports_1.1.1     glue_1.2.0          digest_0.6.12       rvest_0.3.2         colorspace_1.3-2    recipes_0.1.0      
[22] htmltools_0.3.6     Matrix_1.2-9        plyr_1.8.4          devtools_1.13.4     timeDate_3012.100   pkgconfig_2.0.1     CVST_0.2-1         
[29] purrr_0.2.4         scales_0.5.0        gower_0.1.2         lava_1.5.1          git2r_0.19.0        tibble_1.3.4        xgboost_0.6-4      
[36] withr_2.1.0         nnet_7.3-12         lazyeval_0.2.1      survival_2.41-3     magrittr_1.5        memoise_1.1.0       evaluate_0.10.1    
[43] nlme_3.1-131        MASS_7.3-47         xml2_1.1.1          dimRed_0.1.0        class_7.3-14        rsconnect_0.8.5     tools_3.4.0        
[50] data.table_1.10.4-3 hms_0.3             stringr_1.2.0       kernlab_0.9-25      munsell_0.4.3       compiler_3.4.0      RcppRoll_0.2.2     
[57] rlang_0.1.4         grid_3.4.0          base64enc_0.1-3     rmarkdown_1.8       gtable_0.2.0        ModelMetrics_1.1.0  codetools_0.2-15   
[64] curl_3.0            reshape2_1.4.2      R6_2.2.2            lubridate_1.7.1     knitr_1.17          bindr_0.1           rprojroot_1.2      
[71] readr_1.1.1         stringi_1.1.5       rpart_4.1-11        DEoptimR_1.0-8      tidyselect_0.2.3

**Comment by haozhu233** [comment]
Thanks! Fixed now. Sorry for the delay.

**Comment by jgrembi** [comment]
I'm having the same problem described by vancelopez with kableExtra v0.9.0.   My PDF includes \textbf{value} for each value where the ifelse statement evaluates to TRUE.
I tried downloading the latest version from GitHub just now, and it's still not working.
Any suggestions for what I might be doing incorrectly?
